version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:3001"  # Порт 3001 внутри контейнера (по вашим логам), проброшен на 8000 хоста
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true